/** Default generated-image service backed by configured OpenAI-compatible provider routes. */

import { Context, Service } from '@deepseek-ai/cordis'
import z from '@deepseek-ai/schemastery'
import { credentialRef } from '@deepseek-ai/dsh-credentials'
import { assertUsableApiKey } from '@deepseek-ai/dsh-llm'
import { launchEnvironmentOf } from '@deepseek-ai/dsh-launch-environment'
import { installSettingsSection, settingsNamespace } from '@deepseek-ai/dsh-settings'
import type { ImageAttachmentRef } from '@deepseek-ai/dsh-attachment'
import { decodeOpenAiImageResponse, inferImageMediaType, resolveImageEndpoint } from './openai-compatible.ts'

export { decodeOpenAiImageResponse, inferImageMediaType, resolveImageEndpoint } from './openai-compatible.ts'
export type { OpenAiImageResult } from './openai-compatible.ts'

declare module '@deepseek-ai/cordis' {
  interface Context {
    /** Generate an image through the configured auxiliary model route. */
    imageGeneration: ImageGenerationService
  }
}

/** User-settings namespace for the auxiliary image model. */
export const IMAGE_GENERATION_SETTINGS_NAMESPACE = settingsNamespace('image-generation')
const PI_AI_SETTINGS_NAMESPACE = settingsNamespace('llm-pi-ai')
const MAX_PROVIDER_ERROR_MESSAGE = 300

/** Persisted default image route. */
export interface ImageGenerationSettings {
  /** Provider route whose Base URL and credential back image requests. */
  provider: string
  /** Provider-specific model id sent to the Images API. */
  model: string
  /** Relative Images API path resolved against the provider Base URL. */
  endpointPath: string
  /** Relative Images API path used when the request includes reference images. */
  editEndpointPath: string
}

/** Plugin configuration and composition-layer defaults. */
export interface Config extends Partial<ImageGenerationSettings> {
  /** Maximum accepted Images API JSON or downloaded image bytes. */
  maxResponseBytes?: number
}

export const Config: z<Config> = z.object({
  provider: z.string().default(''),
  model: z.string().default(''),
  endpointPath: z.string().default('images/generations'),
  editEndpointPath: z.string().default('images/edits'),
  maxResponseBytes: z.number().step(1).min(1).default(25_000_000),
})

interface PiAiProfile {
  apiKeyEnv?: string
  baseURL?: string
  headers?: Record<string, string>
}

interface PiAiSettings {
  providers?: Record<string, PiAiProfile>
}

/** One generated and durably stored image. */
export interface GeneratedImage {
  /** Provider route that served the image. */
  provider: string
  /** Provider model id that served the image. */
  model: string
  /** Durable attachment reference for the generated bytes. */
  attachment: ImageAttachmentRef
}

/** Provider-neutral request accepted by the generated-image service. */
export interface GenerateImageRequest {
  /** Complete visual description sent to the image provider. */
  prompt: string
  /** Optional provider-supported pixel size. */
  size?: string
  /** Durable images supplied to the provider as edit references. */
  referenceImages?: readonly ImageAttachmentRef[]
  /** Optional provider-supported output quality. */
  quality?: 'low' | 'medium' | 'high'
  /** Cancellation signal for the provider request, download, and attachment save. */
  signal?: AbortSignal
}

function boundedBytes(response: Response, maxResponseBytes: number): Promise<Uint8Array> {
  const declared = response.headers.get('content-length')
  if (declared !== null && Number(declared) > maxResponseBytes) {
    return Promise.reject(new Error('image-generation: provider response exceeds the configured byte limit'))
  }
  return response.arrayBuffer().then((buffer) => {
    if (buffer.byteLength > maxResponseBytes) {
      throw new Error('image-generation: provider response exceeds the configured byte limit')
    }
    return new Uint8Array(buffer)
  })
}

function providerErrorMessage(responseBytes: Uint8Array, apiKey: string | undefined): string | undefined {
  let value: unknown
  try {
    value = JSON.parse(new TextDecoder().decode(responseBytes))
  } catch (_nonJsonProviderBody) {
    return undefined
  }
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return undefined
  const record = value as Record<string, unknown>
  const nested = record.error
  const message = typeof nested === 'object' && nested !== null && !Array.isArray(nested)
    ? (nested as Record<string, unknown>).message
    : record.message
  if (typeof message !== 'string') return undefined
  const normalized = message.replace(/\s+/gu, ' ').trim()
  if (normalized.length === 0) return undefined
  const sanitized = apiKey === undefined ? normalized : normalized.replaceAll(apiKey, '[redacted]')
  return sanitized.slice(0, MAX_PROVIDER_ERROR_MESSAGE)
}

/** Host-owned generated-image capability and OpenAI-compatible provider. */
export class ImageGenerationService extends Service {
  static Config = Config

  private readonly selection: () => ImageGenerationSettings
  private readonly maxResponseBytes: number

  constructor(ctx: Context, config: Config) {
    super(ctx, 'imageGeneration')
    const resolved = config as Required<Config>
    this.maxResponseBytes = resolved.maxResponseBytes
    let current = (): ImageGenerationSettings => ({
      provider: resolved.provider,
      model: resolved.model,
      endpointPath: resolved.endpointPath,
      editEndpointPath: resolved.editEndpointPath,
    })
    this.selection = () => current()
    installSettingsSection(ctx, IMAGE_GENERATION_SETTINGS_NAMESPACE, z.object({
      provider: z.string().default(resolved.provider),
      model: z.string().default(resolved.model),
      endpointPath: z.string().default(resolved.endpointPath),
      editEndpointPath: z.string().default(resolved.editEndpointPath),
    }), current(), {
      validate(value) {
        if ((value.provider.length === 0) !== (value.model.length === 0)) {
          throw new Error('image-generation: provider and model must be configured together')
        }
        resolveImageEndpoint('https://example.invalid/v1', value.endpointPath)
        resolveImageEndpoint('https://example.invalid/v1', value.editEndpointPath)
      },
      setSource(source) { current = source },
      onChange() {},
    })
  }

  /**
   * Generate one image and persist it through the attachment service.
   * @param request - prompt, optional reference images and output controls, and cancellation signal.
   * @returns the serving route plus a durable generated-image attachment.
   */
  async generate(request: GenerateImageRequest): Promise<GeneratedImage> {
    const selection = this.selection()
    if ([selection.provider, selection.model].includes('')) {
      throw new Error('image-generation: configure a default image provider and model in Models settings')
    }
    const settings = this.ctx.get('settings')
    const piAi = settings?.get(PI_AI_SETTINGS_NAMESPACE) as PiAiSettings | undefined
    const profile = piAi?.providers?.[selection.provider]
    if (profile === undefined) {
      throw new Error(`image-generation: provider route ${JSON.stringify(selection.provider)} is not configured`)
    }
    if (!profile.baseURL) {
      throw new Error(`image-generation: provider route ${JSON.stringify(selection.provider)} has no Base URL`)
    }
    const attachments = this.ctx.get('attachments')
    if (attachments === undefined) throw new Error('image-generation: attachment storage is unavailable')

    let apiKey: string | undefined
    if (profile.apiKeyEnv !== undefined) {
      const credentials = this.ctx.get('credentials')
      const hit: string | undefined = credentials !== undefined
        ? (await credentials.resolve(credentialRef(profile.apiKeyEnv)))?.value
        : launchEnvironmentOf(this.ctx).get(profile.apiKeyEnv)?.value
      if (!hit) {
        throw new Error(`image-generation: no credential is stored for ${profile.apiKeyEnv}`)
      }
      apiKey = assertUsableApiKey(hit, 'image-generation', profile.apiKeyEnv)
    }

    const headers = new Headers(profile.headers)
    if (apiKey !== undefined) headers.set('authorization', `Bearer ${apiKey}`)
    const referenceImages = request.referenceImages ?? []
    let body: BodyInit
    if (referenceImages.length === 0) {
      headers.set('content-type', 'application/json')
      body = JSON.stringify({
        model: selection.model,
        prompt: request.prompt,
        n: 1,
        response_format: 'b64_json',
        ...request.size === undefined ? {} : { size: request.size },
        ...request.quality === undefined ? {} : { quality: request.quality },
      })
    } else {
      headers.delete('content-type')
      const storedImages = await Promise.all(referenceImages.map(ref => attachments.readImage(ref, request.signal)))
      const form = new FormData()
      form.set('model', selection.model)
      form.set('prompt', request.prompt)
      if (request.size !== undefined) form.set('size', request.size)
      if (request.quality !== undefined) form.set('quality', request.quality)
      for (const stored of storedImages) {
        const ref = stored.ref
        form.append('image[]', new File([new Uint8Array(stored.data)], ref.name ?? `reference.${ref.mediaType.split('/')[1]}`, {
          type: ref.mediaType,
        }))
      }
      body = form
    }
    const endpoint = resolveImageEndpoint(profile.baseURL,
      referenceImages.length === 0 ? selection.endpointPath : selection.editEndpointPath)
    const response = await fetch(endpoint, {
      method: 'POST',
      headers,
      body,
      ...request.signal === undefined ? {} : { signal: request.signal },
    })
    const responseBytes = await boundedBytes(response, this.maxResponseBytes)
    if (!response.ok) {
      const detail = providerErrorMessage(responseBytes, apiKey)
      throw new Error(`image-generation: provider request failed with HTTP ${String(response.status)}${detail === undefined ? '' : `: ${detail}`}`)
    }
    let decoded: ReturnType<typeof decodeOpenAiImageResponse>
    try {
      decoded = decodeOpenAiImageResponse(JSON.parse(new TextDecoder().decode(responseBytes)))
    } catch (error) {
      throw error
    }
    let data: Uint8Array
    if (decoded.kind === 'bytes') {
      data = decoded.data
    } else {
      const imageResponse = await fetch(decoded.url, request.signal === undefined ? {} : { signal: request.signal })
      if (!imageResponse.ok) {
        throw new Error(`image-generation: image download failed with HTTP ${String(imageResponse.status)}`)
      }
      data = await boundedBytes(imageResponse, this.maxResponseBytes)
    }
    const mediaType = inferImageMediaType(data)
    const attachment = await attachments.saveImage({ data, mediaType, name: `generated.${mediaType.split('/')[1]}` })
    return { provider: selection.provider, model: selection.model, attachment }
  }
}

export default ImageGenerationService
