.git
**/.git

node_modules
**/node_modules

coverage
**/coverage
.nyc_output
**/.nyc_output
.vitest
**/.vitest
.vitest-cache
**/.vitest-cache
test-results
**/test-results
playwright-report
**/playwright-report
**/*.lcov

canvas
canvas/**
**/.canvas-temp
**/.canvas-temp/**

.env
.env.*
**/.env
**/.env.*
